name: ml_ai-training
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.42.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.7.2
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.1.0
      - pillow==10.0.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.12.2
      - six==1.16.0
      - threadpoolctl==3.2.0
      - tzdata==2023.3
      - category_encoders==2.6.2
      - openpyxl==3.1.2
